# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 869c7587a2c1d16a4c797766c1bcfedcc3f1bcdeac80ac6180c71e87ee71c50b6ecb08cc7cbf4f3b2f0be9654ed97d403002caa072a23b6b85dbb04a78978649

test:
  secret_key_base: e160106e09a1c6e9843a09b45f621f2e0cc90d7111b0bf15cfaa702792f0ed31985806a0c82ab5221bf0aa6746ff4b128a174f22831cf68bad7a101b67cd59a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
